### ISSUE TITLE
symbolic link to directory maybe unrecognizable

### ISSUE THREAD

**Issue by Onway** [ArxOne/FTP#14]
I run the unit tests in TestCategory with IIS Ftp Server, all passed except FileExistsTest, 
because there is no key word "FtpEntryType.Link" in WindowsFtpPlatform.ParseLine method. 
In fact, the response lines by STAT command have no symlink identifier. 
![image](https://cloud.githubusercontent.com/assets/3352864/8637673/93a459d4-28d0-11e5-8609-f46a2e059af5.png)

By vsftpd in linux, FileExistsTest passed if symlink to file, but failed to directory, 
because the response line by FtpClient.GetEntry for a folder is always start with 'd', even if the foder is symlink.
So the last Assert statement in FileExistsTest failed. 
![image](https://cloud.githubusercontent.com/assets/3352864/8637688/21af70a6-28d1-11e5-886d-468dd27bda32.png)

**Comment by picrap** [comment]
Thanks! I really need to refine my tests :persevere: 
Do you wanna help? :wink:

**Comment by Onway** [comment]
I dont' know much about the code, but if I can help, I will be glad:grinning:

**Comment by picrap** [comment]
I'm going to open a ticket to refactor tests.
--> https://github.com/ArxOne/FTP/issues/18

**Comment by picrap** [comment]
The ticket will stay closed, but this is just to note here that there is no way to detect symlinks with IIS.
