### ISSUE TITLE
Support "FileExists" method

### ISSUE THREAD

**Issue by danpetitt** [ArxOne/FTP#2]
I need to be able to determine if a file exists and if it does delete it so i can then rename the uploaded file (which was uploaded with a temporary filename).

I would suggest using MLST if its supported for speed as the folder i have to upload to has 30k files in it and is therefore very slow.

I suppose I could just 'delete' the file and ignore the response?

**Comment by picrap** [comment]
To check if a file exists, I used the STAT command. But this can be included in the library anyway. Thanks for suggestion.

**Comment by picrap** [comment]
`FtpClient.GetEntry()` is your new friend (NuGet package 1.1)
