### ISSUE TITLE
intermittent error with a certain server

### ISSUE THREAD

**Issue by ontytoom** [ArxOne/FTP#21]
I have noticed that sometimes I get an error connecting to a certain server: ftp.ch.freebsd.org

Out of 2000 tests, it failed only 8 times..... so, strangely enough, it only happens sometimes.

It reports an error:

```
Impossible to parse line: drwxr-xr-x    1 10000    10000          34 Aug 12 
```

When I look at the server listing for /  I see that the only matching line is:

```
drwxr-xr-x    1 10000    10000          34 Aug 12 00:10 funport
```

The server claims to be vsFTPd 3.0.2

**Comment by ontytoom** [comment]
Test program I used (DebugPrintln is any debugging function of your choice):

```
            int NrTests = 1000;
            int nrSuccess = 0, nrFail = 0;

            for ( int i = 0; i <  NrTests; i++ )
            {
                IEnumerable<FtpEntry> list;

                try
                {
                    list = ftp.ListEntries( "/" );
                    DebugPrintln( list.ToArray().Count().ToString() );
                    nrSuccess++;
                }
                catch ( Exception ex )
                {
                    DebugPrintln( ex.Message );
                    nrFail++;
                }

            }

            DebugPrintln( "Tally: " + NrTests + " tests, of which " + nrSuccess + " passes and " + nrFail + " failed" );
```

**Comment by ontytoom** [comment]
Found on latest library from Nuget

**Comment by picrap** [comment]
It looks like the directory content is not fully transferred, and the data channel is closed before the end. However, I'll take a look at it.

**Comment by picrap** [comment]
Unfortunately, this works for me...
