### ISSUE TITLE
FtpEntry.Data always reports time as 00:00

### ISSUE THREAD

**Issue by ontytoom** [ArxOne/FTP#22]
It seems that the time is always shown as 00:00
If I check ftp folder listings manually, the times are displayed.
Perhaps only the date is parsed but the time is skipped?

This is not a show stopper, but would be nice to have :-)

![image](https://cloud.githubusercontent.com/assets/1593655/9213239/64014ce6-405e-11e5-8a58-3cbcbc0085ad.png)

**Comment by ontytoom** [comment]
I apologize, I think I am wrong.  Time is zero when the server only shows "month day year", but for current year server shows "month day time".

Researching...

**Comment by picrap** [comment]
Are you using `LIST`or `MLSD` to list files? When available, `MLSD` is more accurate.

**Comment by ontytoom** [comment]
I am using ftp.ListEntries(), so I think it's LIST?
I will try MlsdEntries() to see if it helps.
Thank you.

**Comment by picrap** [comment]
:+1: that was the idea
