### ISSUE TITLE
Error parsing Modify fact of Mlsd 

### ISSUE THREAD

**Issue by AndreaCuneo** [ArxOne/FTP#28]
Hi,

I've find out that the format used to parse the Modify field of Mlsd is wrong. It doesn't parse dates with hours greater than 12.

The current formats are: "yyyyMMddhhmmss", "yyyyMMddhhmmss.fff"
They should be: "yyyyMMdd**HH**mmss", "yyyyMMdd**HH**mmss.fff" to correctly handle 00-23

**Comment by picrap** [comment]
Shame. Fixed. Thanks.
