### ISSUE TITLE
FileZilla and STAT command

### ISSUE THREAD

**Issue by darrell-aevum** [ArxOne/FTP#31]
Picrap,
I noticed the command for GetEntry is using the "STAT" command. 
I am unable to use GetEntry with FileZilla because it does not know what the STAT command is.
Also, if I use LIST on a directory that does not exist, it throws an error.

Basically I'm trying to check if a directory exists before renaming a file/folder to that directory.

Any other options than GetEntry or LIST?

Thanks,
Darrell

**Comment by picrap** [comment]
Hi,

Why don't you rely on the exception? If it is thrown, this means that the directory does not exist, right?
Or you could check if the MLSD works.

**Comment by picrap** [comment]
Any news here?

**Comment by picrap** [comment]
💀 ?
🔫 !
