### ISSUE TITLE
ArxOne.Ftp.Exceptions.FtpFileException: File error. Code=550

### ISSUE THREAD

**Issue by lcnvdl** [ArxOne/FTP#37]
I'm getting the next error: ArxOne.Ftp.Exceptions.FtpFileException: File error. Code=550

But only trying to upload the file Views/ABM/Usuarios.cshtml

Please, See my log:

"Subiendo" = "Uploading"

Subiendo...
Subiendo C:\Jenkins\.jenkins\jobs\HalleyV3 - Trunk\workspace\HalleyV3.WebSite\Views\Web.config...
OK

Carpeta: Views
Path: Views//Web.config
Subiendo C:\Jenkins\.jenkins\jobs\HalleyV3 - Trunk\workspace\HalleyV3.WebSite\Views\_ViewStart.cshtml...
OK

Carpeta: Views
Path: Views//_ViewStart.cshtml
Subiendo C:\Jenkins\.jenkins\jobs\HalleyV3 - Trunk\workspace\HalleyV3.WebSite\Views\ABM\Usuarios.cshtml...
OK

Carpeta: Views
Path: Views//ABM/Usuarios.cshtml
ArxOne.Ftp.Exceptions.FtpFileException: File error. Code=550 ('Filename invalid')
   en ArxOne.Ftp.FtpSession.ThrowException(FtpReply reply)
   en ArxOne.Ftp.FtpClientUtility.ProcessStor(FtpSession session, FtpPath path, FtpTransferMode mode)
   en ArxOne.Ftp.FtpClientUtility.<>c__DisplayClass9_0.<Stor>b__0(FtpSession handle)
   en ArxOne.Ftp.FtpClient.Process[TResult](Func`2 action, FtpSession session)
   en ArxOne.Ftp.FtpClientUtility.Stor(FtpClient ftpClient, FtpPath path, FtpTransferMode mode)
   en HalleyVersionPublisher.Publicador.CargarGenerico(String carpetaFtp, String directorio, Boolean recursive, String filtro, String filtroRegex, Boolean eliminarViejos, IEnumerable`1 extensionesValidas) en c:\Jenkins\.jenkins\jobs\Halley V2\workspace\HVP\Publicador.cs:l¡nea 286
   en HVP.Parametros.Procesar(String[] args) en c:\Jenkins\.jenkins\jobs\Halley V2\workspace\HVP\Parametros.cs:l¡nea 109

**Comment by picrap** [comment]
Hi, it is a server error code, so it's hard to tell what fails. Maybe is it related to the fact that you have a double forward slash in the path? Or maybe that the ABM subdirectory does not exist and that the server does not allow it?

**Comment by lcnvdl** [comment]
Thank you for the quick answer. The problem was that the subdirectory doesn't exists. Thanks!
