### ISSUE TITLE
Retrive .odt files

### ISSUE THREAD

**Issue by MrBlackdemon** [ArxOne/FTP#41]
Hi, when i try to retrive an .odt file, the getBinaryReader() return null, in same location of the .odt file, i've got an .doc file, and when i retrive the doc it's work.
Why with .odt does not work?

**Comment by picrap** [comment]
Probably because `getBinaryReader()` does not exist and you've mistaken this project with another one?

**Comment by MrBlackdemon** [comment]
No, usong arxone lib, but solved, my iis mime types was not configured for
.odt files, for this reason getbinaryreader() returned null

Il gio 26 lug 2018, 23:56 Pascal Craponne <notifications@github.com> ha
scritto:
