### ISSUE TITLE
Folder name issue

### ISSUE THREAD

**Issue by Nirad** [ArxOne/FTP#6]
i unable to figure out why am not able to open this style of folder name or any folder with space in it
 /\Fun/Films/Bla Bla Vol. 1 et 2 (2003-2004) MULTi-Work [WORK] XCOM-FunFor

Server is unix

**Comment by Nirad** [comment]
pieces of code 

ftpClient.ListEntries("/\Fun/Films/Bla Bla Vol. 1 et 2 (2003-2004) MULTi-Work [WORK] XCOM-FunFor")

**Comment by Nirad** [comment]
that is my workin solution

```
                    tempPath = tempPath.Replace(" ", @"\ ");
                    tempPath = tempPath.Replace("[", @"\[");
                    tempPath = tempPath.Replace("]", @"\]");
                    tempPath = tempPath.Replace("(", @"\(");
                    tempPath = tempPath.Replace(")", @"\)");
```

**Comment by picrap** [comment]
I made a fix in release 1.2.4.
From my tests, only spaces needed to be fixed.
In your sample there is a backslash. It this normal?
Let me know if it's now OK.

**Comment by Nirad** [comment]
I confirm the spaces work well, but other special characters not. Fillezila works well on the same FTP server. I will continue my testing on another server. Thank you for your very quick response. 
tested ver. 1.2.4

**Comment by Nirad** [comment]
For the backslash I use FtpEntry -> FtpPath entity and this is the way it gives me

**Comment by Nirad** [comment]
/Name/file test.txt = ok
/[Name]/file test.txt = fail

**Comment by picrap** [comment]
I have made a blind fix, released in version 1.2.5... Let me know :wink:

**Comment by Nirad** [comment]
Your blind fix works everything is ok for me. Thx

**Comment by picrap** [comment]
A lucky guess, then :smile:

**Comment by Eleasar** [comment]
i think this fix was not consistentyl applied. In the ftp client "Stat" method it is used. Method "ProcessGetEntry" does not use it though. At least filezilla server does not work for folder containing spaces (server type tells unix emulated by filezilla).

But otherwise really a great library!

**Comment by picrap** [comment]
This is discussed in https://github.com/ArxOne/FTP/issues/7, so I keep this issue closed.
